version: '3.8'

services:
  psql:
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${DB_DATABASE:-ewallet_db}
      POSTGRES_USER: ${DB_USERNAME:-ewallet_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ewallet_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
