CREATE TYPE wallet_type AS ENUM ('IDENTIFIED', 'UNIDENTIFIED');

CREATE TABLE wallets (
    id UUID PRIMARY KEY,
    client_id UUID NOT NULL,
    type wallet_type NOT NULL,
    balance NUMERIC(15, 2) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_wallets_client_id ON wallets(client_id);
