openapi: 3.0.0
info:
  title: E-Wallet API
  version: 1.0.0
  description: API for e-wallet services providing functionality for checking wallets, topping up, viewing statistics, and checking balances.

servers:
  - url: http://127.0.0.1:8080
    description: Local development server

tags:
  - name: wallet
    description: Wallet operations

paths:
  /api/v1/check:
    post:
      summary: Check if a wallet exists
      description: Verifies the existence of a wallet based on the provided wallet ID.
      tags:
        - wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletCheckRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletCheckResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'

  /api/v1/topup:
    post:
      summary: Top up a wallet
      description: Adds funds to a specified wallet, respecting the maximum balance limits for identified and unidentified accounts.
      tags:
        - wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopUpRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopUpResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'

  /api/v1/stats:
    post:
      summary: Get monthly top-up statistics
      description: Retrieves the total number and sum of top-up operations for a specific wallet in a given month and year.
      tags:
        - wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatsRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'

  /api/v1/balance:
    post:
      summary: Get wallet balance
      description: Retrieves the current balance of a specified wallet.
      tags:
        - wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'

components:
  schemas:
    WalletCheckRequest:
      type: object
      properties:
        walletId:
          type: string
          example: "W123456789"
          description: Unique identifier of the wallet
      required:
        - walletId

    WalletCheckResponse:
      type: object
      properties:
        exists:
          type: boolean
          example: true
          description: Indicates whether the wallet exists

    TopUpRequest:
      type: object
      properties:
        walletId:
          type: string
          example: "W123456789"
          description: Unique identifier of the wallet
        amount:
          type: number
          format: float
          minimum: 0.01
          example: 100.50
          description: Amount to top up (in somoni)
      required:
        - walletId
        - amount

    TopUpResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
          description: Indicates whether the top-up was successful
        newBalance:
          type: number
          format: float
          example: 500.75
          description: New balance after the top-up

    StatsRequest:
      type: object
      properties:
        walletId:
          type: string
          example: "W123456789"
          description: Unique identifier of the wallet
        month:
          type: integer
          minimum: 1
          maximum: 12
          example: 8
          description: Month for which to retrieve statistics
        year:
          type: integer
          minimum: 2000
          maximum: 2100
          example: 2024
          description: Year for which to retrieve statistics
      required:
        - walletId
        - month
        - year

    StatsResponse:
      type: object
      properties:
        count:
          type: integer
          example: 5
          description: Number of top-up operations in the specified month
        totalAmount:
          type: number
          format: float
          example: 1000.00
          description: Total amount of top-ups in the specified month (in somoni)

    BalanceRequest:
      type: object
      properties:
        walletId:
          type: string
          example: "W123456789"
          description: Unique identifier of the wallet
      required:
        - walletId

    BalanceResponse:
      type: object
      properties:
        balance:
          type: number
          format: float
          example: 500.75
          description: Current balance of the wallet (in somoni)

    Error:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request parameters"
        details:
          type: string
          example: "WalletId must be a non-empty string"

  responses:
    BadRequest:
      description: Bad request due to invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    UnprocessableEntity:
      description: Unable to process the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    TooManyRequests:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-UserId
    DigestAuth:
      type: apiKey
      in: header
      name: X-Digest

security:
  - ApiKeyAuth: []
    DigestAuth: []

x-rate-limit:
  description: Requests are limited to 100 per minute per API key
  limit: 100
  period: 60
